# http://travis-ci.org/spectralDNS/shenfun

language: generic

os: osx
#osx_image: xcode9.2

sudo: False

env:
  matrix:
    - CONDA_PY=27
    - CONDA_PY=36
    - CONDA_PY=37

  global:
    # "travis encrypt BINSTAR_TOKEN=<token> --repo spectralDNS/shenfun"
    # "travis encrypt CODACY_PROJECT_TOKEN=<token> --repo spectralDNS/shenfun"
    - secure: "Htp2QDvt08yjLNFJknUUhjUTQcoAkDSdFRI5Jq10YZJ52DqZjK4lThY73ckfcfYGinoLCBDJSbrKGEbKszcsZJDhYERe0XZZk4otmHcAH5Q40i94dLlUgceWPHGEtL+f05KWozE4dD4XUhBzOwiQmab2CgxfurR6yY36b1bmReYh+BFaKqFZPnpjQApzsl4rqsQJfJugT7QvwM2uRVioFplFrQL+ukk2TQBQLjyQngA9so8ADJcwWw5m3BhAqS2nJENcX0hdMiwKcR3+MqhF1k+u0UvrIkV1uuSPL0UHKOhRXqMqix2t7d14LShTO0cGKSArsAhZ63IsvOVPgtBA6at8/7RzNHNAazS766d2iczrbF2jbbtXAeKC8OXNKunwhLsDmbHkgiZRdS/xzkITG/klrUbdkveui55P0DbxjZIHMnb78b01cQrCOtV5RaxmZL/c0d6GaXPqP3eheI/S1l8udcqI/qRCKq7DQqUyqhflRvc3hJE3hJn1vFZNSHgJy18iTTxoWIxozpygAT4Hl9jBNE/MD3DuqgDe+a7LqK+HBQCVM3Jdtq/cjZVIZBgpeNhrSvl0iHfrAR0dduxKNzHcFBcNdbZDyjm4dCKDGrcGLpuxJQD2HaNZzVbzhCZFz/swxDuNzTdrAHw6FEd5T7HcHOfZty79EJolBRJXdjQ="
    - secure: "i3252oxITpFfgkBZVPa/1/llFGr874jjk/nIH88MQPcLxP0rw6vP4oO1UjQeLKiOfdjIYVAJx6I2dWhui7jW3m32JUVPZmmtUmkHwqAV1FjHiIZxaQju+wI8pDrhKsY27uNzuLwfTWhiW3NXXJY6CC80PHCon2KCW8Uq/q1mJqBqnyQFH5nALYSM23rCdwqOld4M9Dv7F4KjvuDRcHeLe/qyxkdLncz5+CciQaYhotfSZF1E0ir6LotYsfPdt9z1jlVVUxfDFFYGaS2ajX5Ao6jjWDrrdUF2tfyOe/8TOk+y2Tk36NYA/5k4a9v9wleKqDt4NvtHeMTwpPBu7Usk5uw+oai5hoaFJb9TP/8Y+98KpmXdBLZKmXloOyggVKNQ5Ff3ot8pLoszPpheNcpY+qT+n6o0CQludlQBaGBQkf8Y/W+5BHnxWSRNhJ6+FNXvArNk3UaVMVBzuyVWS/PV5NxRkBhb6L3Qk/9E5ByK5sAHOBpYO0yRTeloNzbIbe8ZBTt+iy7OQsoyFsAXuI/IT0hEfjAMSZzLFAarqAFpAf0PG8GF24qDzLkXJE9wrzcgyzqEBzJRPL0qp/QmMqNZtvNTGw+ecKRYKJ1PthMGxXwiHfJEMRrqwzbIwId7BnrdIgW2eEoRIrharXPFDAFt8+TqUXPYcNw7zFVFfjt20hQ="

before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b
      source /Users/travis/miniconda3/bin/activate root
      conda config --set always_yes yes
      conda config --set show_channel_urls true
      conda config --add channels conda-forge
      conda config --add channels spectralDNS
      conda install -n root conda-build=3.17
      pip install codecov pytest-cov pytest codacy-coverage

script:
    - |
      if [ $CONDA_PY == 37 ]; then
          conda build --no-test --python 3.7 conf/conda
          conda install shenfun --use-local
          py.test --cov=$(python -c "import site; print(site.getsitepackages()[0]+'/shenfun')") --cov-report=xml tests/
      elif [ $CONDA_PY == 36 ]; then
          conda build --python 3.6 conf/conda
      else
          conda build --python 2.7 conf/conda
      fi

after_success:
    - |
      if [ $CONDA_PY == 37 ]; then
          codecov
          python-codacy-coverage -r coverage.xml
      fi
