name: shenfun_doc_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  - cython
  - fftw
  - numpy
  - sympy
  - pyyaml
  - scipy
  - mpi4py
  - mpi4py-fft
  - Sphinx==4.2
  - nbsphinx
  - pip:
    - sphinxcontrib-bibtex
